"""empty message

Revision ID: 41a8d9a2e853
Revises: e6c232f3f080
Create Date: 2021-05-29 17:43:47.349499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a8d9a2e853'
down_revision = 'e6c232f3f080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('Show', sa.Column('id', sa.INTEGER(), nullable=False), 
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.alter_column('Show', 'venue_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('Show', 'artist_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('Show')
    # op.alter_column('Show', 'artist_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('Show', 'venue_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.drop_column('Show', 'id')
    # ### end Alembic commands ###
