"""empty message

Revision ID: 99b23a0a626d
Revises: 6d6e7a597da0
Create Date: 2021-05-21 14:57:03.092350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b23a0a626d'
down_revision = '6d6e7a597da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('state_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'City', 'State', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'City', type_='foreignkey')
    op.drop_column('City', 'state_id')
    # ### end Alembic commands ###
