"""empty message

Revision ID: e6c232f3f080
Revises: 99b23a0a626d
Create Date: 2021-05-29 13:06:30.763971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c232f3f080'
down_revision = '99b23a0a626d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('availability_start', sa.Time(), nullable=True))
    op.add_column('Artist', sa.Column('availability_end', sa.Time(), nullable=True))
    op.drop_constraint('City_name_key', 'City', type_='unique')
    op.add_column('Show', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'end_time')
    op.create_unique_constraint('City_name_key', 'City', ['name'])
    op.drop_column('Artist', 'availability_end')
    op.drop_column('Artist', 'availability_start')
    # ### end Alembic commands ###
